### PR TITLE
Use PhantomJS 2.x.

### PR DESCRIPTION
**Pull request by yjwong**
This pull request allows directory-colorfy to work with PhantomJS 2.x. I'm not sure if such a change is desirable, let me know if you think it's ok.

### CODE REVIEW

**Comment by jefflembeck** [comment]
I'd love to pull in https://github.com/filamentgroup/directory-colorfy/pull/23/commits/764beeeb9b22d4750191800855c9189596c99ad9 - I'll separate them when I can or you can do it :grin:

**Comment by yjwong** [comment]
Ok, I think I will just rebase 764beee on the current master :+1: 

Then I'll split out the dependency updates to separate PRs. Was quite wary of `lodash` especially.

**Comment by gido** [comment]
Can I help on this one ?

Since Medium/phantomjs#522 we have trouble to download the version `1.9.15` of phantomjs.
Issue #20 and #22 was closed, I try my chance here :D

**Comment by rnsloan** [comment]
Would it be possible to create a release for this change? Failures when downloading the PhantomJS binary from bitbucket are a pain and this version of PhantomJS has switched to using github.

**Pull request merged**
